LIBRETRO_DIR      := $(CORE_DIR)/libretro
INCFLAGS          :=

SOURCES_C += $(LIBRETRO_DIR)/libretro.c

PROJECT_SRC_DIR := $(CORE_DIR)

INCFLAGS += $(foreach dir,$(PROJECT_SRC_DIR),-I$(dir)) -I$(LIBRETRO_DIR)

SOURCES_C += $(foreach dir,$(PROJECT_SRC_DIR),$(wildcard $(dir)/*.c))

LDFLAGS += -lprotobuf-c
