# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scene.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'scene.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bscene.proto\"\xa6\x01\n\x05Scene\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\x12\x0e\n\x06pixels\x18\x03 \x01(\x0c\x12\x0f\n\x07palette\x18\x04 \x03(\r\x12\x1c\n\x06\x63ycles\x18\x05 \x03(\x0b\x32\x0c.Scene.Cycle\x1a?\n\x05\x43ycle\x12\r\n\x05\x66lags\x18\x01 \x01(\r\x12\x0c\n\x04rate\x18\x02 \x01(\r\x12\x0b\n\x03low\x18\x03 \x01(\r\x12\x0c\n\x04high\x18\x04 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scene_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCENE']._serialized_start=16
  _globals['_SCENE']._serialized_end=182
  _globals['_SCENE_CYCLE']._serialized_start=119
  _globals['_SCENE_CYCLE']._serialized_end=182
# @@protoc_insertion_point(module_scope)
